// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC464VPQgF_LWwnte0VKAnMNqmlJ6xgU6U',
    appId: '1:301892458712:web:e5602a22ebc2493c6c9fad',
    messagingSenderId: '301892458712',
    projectId: 'recipe-firebase-988e2',
    authDomain: 'recipe-firebase-988e2.firebaseapp.com',
    storageBucket: 'recipe-firebase-988e2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0TeKTHRnPR6YzppvzDPaltBzEfUA-2TA',
    appId: '1:301892458712:android:bf366abe96ef96af6c9fad',
    messagingSenderId: '301892458712',
    projectId: 'recipe-firebase-988e2',
    storageBucket: 'recipe-firebase-988e2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXO83kdtkUGhtguv-39E_PR8o_Lbt7iz4',
    appId: '1:301892458712:ios:0d6b01d8009bbc1a6c9fad',
    messagingSenderId: '301892458712',
    projectId: 'recipe-firebase-988e2',
    storageBucket: 'recipe-firebase-988e2.firebasestorage.app',
    iosBundleId: 'com.example.recipesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXO83kdtkUGhtguv-39E_PR8o_Lbt7iz4',
    appId: '1:301892458712:ios:0d6b01d8009bbc1a6c9fad',
    messagingSenderId: '301892458712',
    projectId: 'recipe-firebase-988e2',
    storageBucket: 'recipe-firebase-988e2.firebasestorage.app',
    iosBundleId: 'com.example.recipesApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC464VPQgF_LWwnte0VKAnMNqmlJ6xgU6U',
    appId: '1:301892458712:web:61bb48128a38fe856c9fad',
    messagingSenderId: '301892458712',
    projectId: 'recipe-firebase-988e2',
    authDomain: 'recipe-firebase-988e2.firebaseapp.com',
    storageBucket: 'recipe-firebase-988e2.firebasestorage.app',
  );

}